//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prestarter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prestarter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос к BellSoft API.
        /// </summary>
        internal static string BellsoftJavaDownloader_ApiRequestStart {
            get {
                return ResourceManager.GetString("BellsoftJavaDownloader_ApiRequestStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка ответа от BellSoft API.
        /// </summary>
        internal static string BellsoftJavaDownloader_ApiResponseProcessing {
            get {
                return ResourceManager.GetString("BellsoftJavaDownloader_ApiResponseProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка во время инициализации: сервер вернул код {0}.
        /// </summary>
        internal static string JavaDownloader_ApiRequestException {
            get {
                return ResourceManager.GetString("JavaDownloader_ApiRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка во время обработки ответа.
        /// </summary>
        internal static string JavaDownloader_ApiResponseProcessingException {
            get {
                return ResourceManager.GetString("JavaDownloader_ApiResponseProcessingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачивание {0}.
        /// </summary>
        internal static string JavaDownloader_Downloading {
            get {
                return ResourceManager.GetString("JavaDownloader_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление старой Java.
        /// </summary>
        internal static string JavaDownloader_RemovingOldJava {
            get {
                return ResourceManager.GetString("JavaDownloader_RemovingOldJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распаковка {0}.
        /// </summary>
        internal static string JavaDownloader_Unpacking {
            get {
                return ResourceManager.GetString("JavaDownloader_Unpacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для запуска лаунчера {0} необходимо программное обеспечение Java. Скачать {1}?.
        /// </summary>
        internal static string Prestarter_JavaDownloadPrompt {
            get {
                return ResourceManager.GetString("Prestarter_JavaDownloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно обновление Java. Обновить?.
        /// </summary>
        internal static string Prestarter_JavaUpdatePrompt {
            get {
                return ResourceManager.GetString("Prestarter_JavaUpdatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процесс лаунчера закрылся слишком быстро.
        /// </summary>
        internal static string Prestarter_StartJvm_ProcessExitedEarly {
            get {
                return ResourceManager.GetString("Prestarter_StartJvm_ProcessExitedEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск.
        /// </summary>
        internal static string Prestarter_Step_Launch {
            get {
                return ResourceManager.GetString("Prestarter_Step_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачивание лаунчера.
        /// </summary>
        internal static string Prestarter_Step_LauncherDownload {
            get {
                return ResourceManager.GetString("Prestarter_Step_LauncherDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск лаунчера.
        /// </summary>
        internal static string Prestarter_Step_LauncherSearch {
            get {
                return ResourceManager.GetString("Prestarter_Step_LauncherSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось найти {0}.
        /// </summary>
        internal static string RuntimeDownloaderFactory_DownloaderNotFound {
            get {
                return ResourceManager.GetString("RuntimeDownloaderFactory_DownloaderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос к Azul API.
        /// </summary>
        internal static string ZuluJavaDownloader_ApiRequest {
            get {
                return ResourceManager.GetString("ZuluJavaDownloader_ApiRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка ответа от Azul API.
        /// </summary>
        internal static string ZuluJavaDownloader_ApiResponseProcessing {
            get {
                return ResourceManager.GetString("ZuluJavaDownloader_ApiResponseProcessing", resourceCulture);
            }
        }
    }
}
